---
title: "Car prices"
subtitle: "SIM project"
author:
    - Aleix Boné
    - David Gili
tables: true
output:
    pdf_document:
        latex_engine: lualatex
        fig_caption: true
        number_sections: true
        dev: cairo_pdf
        includes:
            in_header: preamble.tex
        extra_dependencies: [ "float", "cleveref" , "multicol"]
        keep_tex: true
        pandoc_args: "--pdf-engine-opt=-shell-escape"
    html_document:
        toc: true
        toc_float:
            collapsed: false
            smooth_scroll: true
urlcolor: blue
---

```{r include = FALSE}
library(knitr)
library(kableExtra)

options(encoding = "UTF-8")
options(knitr.table.format = function() {
    if (knitr::is_latex_output()) "latex" else "pipe"
})
if (isTRUE(getOption("knitr.in.progress"))) {
    options(width = 80)
    # NOTE: This will still affect the options if you use the same R session
    # after running knitr
}

knitr::opts_chunk$set(
    echo = FALSE,
    collapse = FALSE,
    comment = "#>",
    fig.retina = 2, # Control using dpi
    fig.width = 5, # generated images
    fig.height = 3, # generated images
    fig.pos = "H", # pdf mode
    fig.align = "center",
    dpi = if (knitr::is_latex_output()) 72 else 300,
    out.width = "100%",
    optipng = "-o1 -quiet"
)

output_hook <- function(x, options) {
    x <- paste0(x, collapse = "\n")
    paste("\\begin{shaded}", "\\begin{verbatim}", x, "\\end{verbatim}", "\\end{shaded}", sep = "\n")
}
knit_hooks$set(output = output_hook)
```

\thispagestyle{empty}
\setcounter{page}{0}
\null
\vspace{5em}
\tableofcontents
\pagebreak

```{r configure_minted, include = FALSE}
if (knitr::is_latex_output()) {
    if (Sys.which("pygmentize") != "") {
        minted_hook <- function(x, options) {
            x <- paste0(x, collapse = "\n")
            paste("\\begin{minted}{R}", x, "\\end{minted}", sep = "\n")
        }
        usepackage_latex("minted")
        knit_hooks$set(source = minted_hook)
        options(tinytex.engine_args = "-shell-escape")
    }
}
```

```{r child = 'data_preparation.Rmd'}
# Preprocessing
```

\renewcommand\thesubsection{\arabic{subsection}.}

\pagebreak
```{r child = 'questions.Rmd'}
# Questions
```
